import { db } from "@/lib/db";
import { auth, clerkClient } from "@clerk/nextjs/server";
import { NextRequest, NextResponse } from "next/server";
import bcrypt from "bcryptjs";
import crypto from "crypto";

/**
 * POST /api/auth/recovery-code/generate
 *
 * Generates a new recovery code for the authenticated super admin.
 * The plain code is returned ONCE and never stored.
 * The bcrypt hash is stored in RecoveryCode table.
 *
 * Format: MX-XXXX-XXXX-XXXX (cryptographically random)
 */
export async function POST(_request: NextRequest) {
  const { userId } = await auth();
  if (!userId) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }

  const user = await db.user.findUnique({
    where: { clerkId: userId },
    include: { Role: { select: { name: true } } },
  });

  if (!user || user.Role.name !== "super_admin") {
    return NextResponse.json(
      { error: "Recovery codes can only be generated by super admins" },
      { status: 403 }
    );
  }

  // Invalidate any existing unused recovery codes for this user
  await db.recoveryCode.deleteMany({
    where: { userId: user.id, usedAt: null },
  });

  // Generate a cryptographically random code: MX-XXXX-XXXX-XXXX
  const segment = () => crypto.randomBytes(2).toString("hex").toUpperCase();
  const plainCode = `MX-${segment()}-${segment()}-${segment()}`;

  // Hash with bcrypt (cost factor 12)
  const codeHash = await bcrypt.hash(plainCode, 12);

  await db.recoveryCode.create({
    data: {
      userId: user.id,
      codeHash,
    },
  });

  // Return plain code ONE TIME ONLY
  return NextResponse.json({
    code: plainCode,
    warning: "Store this code securely. It will not be shown again.",
    format: "MX-XXXX-XXXX-XXXX",
  });
}
